import{initializeApp}from "https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js";import{getAuth,signInAnonymously,signInWithCustomToken,onAuthStateChanged,signOut}
from "https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js";import{getFirestore,doc,setDoc,onSnapshot,increment,setLogLevel,getDoc}from "https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js";setLogLevel('Debug');const appId=typeof __app_id!=='undefined'?__app_id:'default-app-id';const firebaseConfig=typeof __firebase_config!=='undefined'?JSON.parse(__firebase_config):{apiKey:"AIzaSyBbvImpR3KnEMpwI8VVrOJg3pwcQbq12Qc",authDomain:"autoresonderwa.firebaseapp.com",projectId:"autoresonderwa",storageBucket:"autoresonderwa.firebasestorage.app",messagingSenderId:"865886495056",appId:"1:865886495056:android:1268855d193bb3a781cc55"};const initialAuthToken=typeof __initial_auth_token!=='undefined'?__initial_auth_token:null;const ERROR_APP_ID="originalamanah-my-id";const EXTERNAL_FIREBASE_CONFIG={apiKey:"AIzaSyDS6reCDJnak8YaUXs9tHx9c_sBg3G7hGY/hapus",authDomain:"global-project-fe765.firebaseapp.com",projectId:"global-project-fe765",storageBucket:"global-project-fe765.firebasestorage.app",messagingSenderId:"776529586347",appId:"1:776529586347:web:bb291d721d788fdaea2fee",measurementId:"G-YV9KS75YJF"};const EXTERNAL_COUNTER_DOC_PATH=`/globalpro_counters/${ERROR_APP_ID}/counters/main_counter`;let mainDb,mainAuth;let mainUserId=null;let listenersInitialized=!1;let globalPromoMessage="";const PROMO_TEXT_DOC_PATH=`/artifacts/${appId}/public/data/config/homepage_text`;const PREORDER_TERMS_DOC_PATH=`/artifacts/${appId}/public/data/config/preorder_terms`;const ORDER_PROCESS_DOC_PATH=`/artifacts/${appId}/public/data/config/order_process`;const PREORDER_HEADER_DOC_PATH=`/artifacts/${appId}/public/data/config/preorder_header`;const MAIN_TITLE_DOC_PATH=`/artifacts/${appId}/public/data/config/order_header`;const UP_DATE_DOC_PATH=`/artifacts/${appId}/public/data/config/order_date`;const ST_ARS_DOC_PATH=`/artifacts/${appId}/public/data/config/order_stars`;const KONSUL_DOC_PATH=`/artifacts/${appId}/public/data/config/order_konsul`;function formatCount(num){if(num>=1000000){return(num/1000000).toFixed(1).replace(/\.0$/,'')+'jt'}
if(num>=100000){return(num/1000).toFixed(0)+'rb'}
if(num>=1000){return(num/1000).toFixed(1).replace(/\.0$/,'')+'k'}
return num.toString()}
function updatePromoTextUI(message){const realtimeTextElement=document.getElementById('realtime-text');if(!realtimeTextElement)return;globalPromoMessage=message?message.trim():"";if(globalPromoMessage.length>0){let displayMessage=globalPromoMessage;if(mainAuth.currentUser&&mainAuth.currentUser.uid){displayMessage=`Halo kak, ${globalPromoMessage}`;realtimeTextElement.classList.remove('bg-yellow-100','border-yellow-300');realtimeTextElement.classList.add('bg-green-100','border-green-300')}else{displayMessage=`Anda belum login. ${globalPromoMessage}`;realtimeTextElement.classList.remove('bg-green-100','border-green-300');realtimeTextElement.classList.add('bg-yellow-100','border-yellow-300')}
realtimeTextElement.textContent=displayMessage;realtimeTextElement.style.display='block';console.log('[Main App] Teks promosi real-time diperbarui. Ditampilkan.')}else{console.log('[Main App] Teks promosi tidak tersedia. Disembunyikan.');realtimeTextElement.style.display='none'}}
async function setVisitorCountManually(newCount){try{const app=initializeApp(EXTERNAL_FIREBASE_CONFIG,"admin-counter-setter");const db=getFirestore(app);if(typeof newCount!=='number'||newCount<0){console.error("Nilai counter harus berupa angka positif.");return}
const counterRef=doc(db,EXTERNAL_COUNTER_DOC_PATH);await setDoc(counterRef,{count:newCount});console.log(`[Counter Admin] Jumlah pengunjung berhasil diatur secara manual ke: ${newCount} (Firebase Eksternal)`)}catch(error){console.error("[Counter Admin] Error mengatur jumlah pengunjung secara manual: ",error)}}
window.setVisitorCountManually=setVisitorCountManually;async function initializeExternalVisitorCounter(){let externalDb,externalAuth;const DELAY_MS=1200;try{const app=initializeApp(EXTERNAL_FIREBASE_CONFIG,"visitor-counter-app");externalDb=getFirestore(app);externalAuth=getAuth(app);     
        
await signInAnonymously(externalAuth);console.log('[Counter External] Firebase auth (anonymous) successful.');const counterRef=doc(externalDb,EXTERNAL_COUNTER_DOC_PATH);const countElement=document.getElementById('visitor-count');        
if(!countElement){console.warn("[Counter External] Elemen 'visitor-count' tidak ditemukan. Gagal menerapkan delay.")}else{setTimeout(()=>{countElement.classList.remove('hidden');console.log(`[Counter External] Visitor Count ditampilkan setelah delay ${DELAY_MS}ms.`)},DELAY_MS)}
onSnapshot(counterRef,(doc)=>{let count=0;if(doc.exists()){count=doc.data().count}
countElement.textContent=formatCount(count);console.log(`[Counter External] Jumlah pengunjung ditampilkan: ${count}`)},(error)=>{console.error("[Counter External] Error listening to counter snapshot: ",error);countElement.textContent='Error'});  
        
await setDoc(counterRef,{count:increment(1)},{merge:!0});console.log('[Counter External] Jumlah pengunjung berhasil ditingkatkan.')}catch(error){console.error("[Counter External] Error initializing Firebase or visitor counter: ",error);const countElement=document.getElementById('visitor-count');if(countElement){countElement.textContent='N/A'}}}
function startMainAppRealtimeListeners(){if(listenersInitialized){console.log("[Main App] Realtime listeners sudah diinisialisasi. Melewati.");return}
listenersInitialized=!0;console.log("[Main App] Memulai inisialisasi Realtime listeners...");const promoTextRef=doc(mainDb,PROMO_TEXT_DOC_PATH);const realtimeTextElement=document.getElementById('realtime-text');if(!realtimeTextElement){console.error("[Main App] Elemen 'realtime-text' tidak ditemukan.");return}
onSnapshot(promoTextRef,(doc)=>{let message="";if(doc.exists()&&doc.data().message){message=doc.data().message}
updatePromoTextUI(message)},(error)=>{console.error("[Main App] Error listening to promo text snapshot: ",error);realtimeTextElement.textContent='Error memuat pesan dinamis.';realtimeTextElement.style.display='block'});getDoc(promoTextRef).then(docSnap=>{if(!docSnap.exists()){setDoc(promoTextRef,{message:""}).then(()=>console.log("[Main App] Konfigurasi promo default (kosong) disimpan.")).catch(err=>console.error("[Main App] Error saving default promo config: ",err))}});const mainTitleRef=doc(mainDb,MAIN_TITLE_DOC_PATH);const mainTitleElement=document.getElementById('maintitle');const defaultMainTitleText=``;if(!mainTitleElement){console.error("[Main App] Elemen 'maintitle' tidak ditemukan.")}else{onSnapshot(mainTitleRef,(doc)=>{if(doc.exists()&&doc.data().headerText){mainTitleElement.textContent=doc.data().headerText;console.log(`[Main App] Judul Utama (ID: maintitle) berhasil diperbarui: ${doc.data().headerText}`)}else{mainTitleElement.textContent=defaultMainTitleText;console.log('[Main App] Judul Utama (ID: maintitle) tidak ditemukan, menggunakan default.')}},(error)=>{console.error("[Main App] Error listening to main title snapshot: ",error);mainTitleElement.textContent=`Error: ${defaultMainTitleText}`});getDoc(mainTitleRef).then(docSnap=>{if(!docSnap.exists()){setDoc(mainTitleRef,{headerText:defaultMainTitleText}).then(()=>console.log("[Main App] Konfigurasi judul utama default disimpan.")).catch(err=>console.error("[Main App] Error saving default main title config: ",err))}})}
const upDateRef=doc(mainDb,UP_DATE_DOC_PATH);const upDateElement=document.getElementById('Update');const defaultUpDateText=``;if(!upDateElement){console.error("[Main App] Elemen 'maintitle' tidak ditemukan.")}else{onSnapshot(upDateRef,(doc)=>{if(doc.exists()&&doc.data().headerText){upDateElement.textContent=doc.data().headerText;console.log(`[Main App] Judul Utama (ID: maintitle) berhasil diperbarui: ${doc.data().headerText}`)}else{upDateElement.textContent=defaultUpDateText;console.log('[Main App] Judul Utama (ID: maintitle) tidak ditemukan, menggunakan default.')}},(error)=>{console.error("[Main App] Error listening to main title snapshot: ",error);upDateElement.textContent=`Error: ${defaultUpDateText}`});getDoc(upDateRef).then(docSnap=>{if(!docSnap.exists()){setDoc(upDateRef,{headerText:defaultUpDateText}).then(()=>console.log("[Main App] Konfigurasi judul utama default disimpan.")).catch(err=>console.error("[Main App] Error saving default main title config: ",err))}})}
const stArsRef=doc(mainDb,ST_ARS_DOC_PATH);const stArsElement=document.getElementById('stars');const defaultstArsText=`...`;if(!stArsElement){console.error("[Main App] Elemen 'maintitle' tidak ditemukan.")}else{onSnapshot(stArsRef,(doc)=>{if(doc.exists()&&doc.data().headerText){stArsElement.textContent=doc.data().headerText;console.log(`[Main App] Judul Utama (ID: maintitle) berhasil diperbarui: ${doc.data().headerText}`)}else{stArsElement.textContent=defaultstArsText;console.log('[Main App] Judul Utama (ID: maintitle) tidak ditemukan, menggunakan default.')}},(error)=>{console.error("[Main App] Error listening to main title snapshot: ",error);stArsElement.textContent=`Error: ${defaultstArsText}`});getDoc(stArsRef).then(docSnap=>{if(!docSnap.exists()){setDoc(stArsRef,{headerText:defaultstArsText}).then(()=>console.log("[Main App] Konfigurasi judul utama default disimpan.")).catch(err=>console.error("[Main App] Error saving default main title config: ",err))}})}
const konSulRef=doc(mainDb,KONSUL_DOC_PATH);const konSulElement=document.getElementById('konsul');const defaultkonSulText=`...`;if(!konSulElement){console.error("[Main App] Elemen 'maintitle' tidak ditemukan.")}else{onSnapshot(konSulRef,(doc)=>{if(doc.exists()&&doc.data().headerText){konSulElement.textContent=doc.data().headerText;console.log(`[Main App] Judul Utama (ID: maintitle) berhasil diperbarui: ${doc.data().headerText}`)}else{konSulElement.textContent=defaultkonSulText;console.log('[Main App] Judul Utama (ID: maintitle) tidak ditemukan, menggunakan default.')}},(error)=>{console.error("[Main App] Error listening to main title snapshot: ",error);konSulElement.textContent=`Error: ${defaultkonSulText}`});getDoc(konSulRef).then(docSnap=>{if(!docSnap.exists()){setDoc(konSulRef,{headerText:defaultkonSulText}).then(()=>console.log("[Main App] Konfigurasi judul utama default disimpan.")).catch(err=>console.error("[Main App] Error saving default main title config: ",err))}})}
const termsHeaderRef=doc(mainDb,PREORDER_HEADER_DOC_PATH);const termsHeaderElement=document.getElementById('pra-txt');const defaultHeaderText=`<u>Ketentuan Pra-Pemesanan:</u>`;if(!termsHeaderElement){console.error("[Main App] Elemen 'pra-txt' tidak ditemukan.");return}
onSnapshot(termsHeaderRef,(doc)=>{if(doc.exists()&&doc.data().headerText){termsHeaderElement.innerHTML=doc.data().headerText;console.log('[Main App] Teks header pra-pemesanan real-time diperbarui.')}else{termsHeaderElement.innerHTML=defaultHeaderText;console.log('[Main App] Teks header pra-pemesanan tidak ditemukan, menggunakan default.')}},(error)=>{console.error("[Main App] Error listening to terms header snapshot: ",error);termsHeaderElement.innerHTML=`<span class="text-red-500">Gagal memuat judul.</span> ${defaultHeaderText}`});getDoc(termsHeaderRef).then(docSnap=>{if(!docSnap.exists()){setDoc(termsHeaderRef,{headerText:defaultHeaderText}).then(()=>console.log("[Main App] Konfigurasi header default disimpan.")).catch(err=>console.error("[Main App] Error saving default terms header config: ",err))}});const termsListRef=doc(mainDb,PREORDER_TERMS_DOC_PATH);const termsContainer=document.getElementById('preorder-terms-container');if(!termsContainer){console.error("[Main App] Elemen 'preorder-terms-container' tidak ditemukan.");return}
const defaultTermsHtml=`
<ul class="list-disc pl-5 space-y-2 text-gray-600">
<li>Pembayaran DP minimal 50% harus dilakukan di awal.</li>
<li>Waktu tunggu produk Pre-Order adalah 2-3 minggu kerja.</li>
<li>Pembatalan sepihak setelah DP akan mengakibatkan DP hangus.</li>
<li>Sisa pembayaran dilunasi saat barang siap kirim atau diambil.</li>
</ul>`;onSnapshot(termsListRef,(doc)=>{if(doc.exists()&&doc.data().listHtml){termsContainer.innerHTML=doc.data().listHtml;termsContainer.classList.remove('text-gray-500');console.log('[Main App] Daftar ketentuan real-time berhasil diperbarui.')}else{termsContainer.innerHTML=defaultTermsHtml;termsContainer.classList.remove('text-gray-500');console.log('[Main App] Daftar ketentuan tidak ditemukan, menggunakan default HTML list.')}},(error)=>{console.error("[Main App] Error listening to terms snapshot: ",error);termsContainer.innerHTML=`<p class="text-red-500">Gagal memuat ketentuan dari server. Menampilkan default...</p>${defaultTermsHtml}`});getDoc(termsListRef).then(docSnap=>{if(!docSnap.exists()){setDoc(termsListRef,{listHtml:defaultTermsHtml.trim()}).then(()=>console.log("[Main App] Konfigurasi ketentuan default disimpan.")).catch(err=>console.error("[Main App] Error saving default terms config: ",err))}});const orderProcessRef=doc(mainDb,ORDER_PROCESS_DOC_PATH);const orderProcessElement=document.getElementById('order-process-text');if(!orderProcessElement){console.error("[Main App] Elemen 'order-process-text' tidak ditemukan.");return}
onSnapshot(orderProcessRef,(doc)=>{if(doc.exists()&&doc.data().processText){orderProcessElement.innerHTML=doc.data().processText;console.log('[Main App] Teks proses order real-time diperbarui.')}else{orderProcessElement.innerHTML='Cara order tidak dapat dimuat atau belum diatur.';console.log('[Main App] Teks proses order tidak ditemukan atau belum diatur.')}},(error)=>{console.error("[Main App] Error listening to order process snapshot: ",error);orderProcessElement.innerHTML='Gagal memuat teks proses order dari server.'});getDoc(orderProcessRef).then(docSnap=>{if(!docSnap.exists()){const defaultText=``;setDoc(orderProcessRef,{processText:defaultText}).then(()=>console.log("[Main App] Konfigurasi proses order default disimpan.")).catch(err=>console.error("[Main App] Error saving default order process config: ",err))}})}
async function initializeMainFirebaseApp(){try{const app=initializeApp(firebaseConfig,"main-app");mainDb=getFirestore(app);mainAuth=getAuth(app);const authButton=document.getElementById('auth-button');if(initialAuthToken){await signInWithCustomToken(mainAuth,initialAuthToken);console.log('[Main App] Firebase auth (custom token) successful.')}else{await signInAnonymously(mainAuth);console.log('[Main App] Firebase auth (anonymous) successful.')}
const homesElement=document.getElementById('homes');const starElement=document.getElementById('yourstar');const eyesElement=document.getElementById('eyes');const starsElement=document.getElementById('stars');const linesElement=document.getElementById('lines');const sectionisElement=document.getElementById('sectionis');if(homesElement||starElement){setTimeout(()=>{if(homesElement){homesElement.classList.remove('hidden');console.log('[Main App] Tombol Home ditemukan dan kelas "hidden" telah dihapus setelah delay 500ms.')}
if(starElement){starElement.classList.remove('hidden');console.log('[Main App] Bintang SVG ditemukan dan kelas "hidden" telah dihapus setelah delay 500ms.')}
if(eyesElement){eyesElement.classList.remove('hidden');console.log('[Main App] Bintang SVG ditemukan dan kelas "hidden" telah dihapus setelah delay 500ms.')}
if(starsElement){starsElement.classList.remove('hidden');console.log('[Main App] Bintang SVG ditemukan dan kelas "hidden" telah dihapus setelah delay 500ms.')}
if(linesElement){linesElement.classList.remove('hidden');console.log('[Main App] Bintang SVG ditemukan dan kelas "hidden" telah dihapus setelah delay 500ms.')}
if(sectionisElement){sectionisElement.classList.remove('hidden');console.log('[Main App] Bintang SVG ditemukan dan kelas "hidden" telah dihapus setelah delay 500ms.')}},800)}else{console.error('[Main App] GAGAL KRITIS: Elemen tombol Home ("homes") dan Bintang ("yourstar") TIDAK ditemukan di DOM.')}
startMainAppRealtimeListeners();onAuthStateChanged(mainAuth,(user)=>{if(user){mainUserId=user.uid;authButton.textContent='Keluar (UID: '+mainUserId.substring(0,4)+'...)';authButton.classList.remove('bg-green-500','hover:bg-green-600');authButton.classList.add('bg-red-500','hover:bg-red-600');console.log(`[Main App] User is signed in. UID: ${mainUserId}`)}else{mainUserId=null;authButton.textContent='Masuk / Daftar';authButton.classList.remove('bg-red-500','hover:bg-red-600');authButton.classList.add('bg-green-500','hover:bg-green-600');console.log('[Main App] User is signed out.')}
if(globalPromoMessage){updatePromoTextUI(globalPromoMessage)}});authButton.addEventListener('click',async()=>{if(mainAuth.currentUser){try{await signOut(mainAuth);console.log('[Main App] Sign out successful.')}catch(error){console.error('[Main App] Error signing out:',error)}}else{try{await signInAnonymously(mainAuth);console.log('[Main App] Signed in anonymously.')}catch(error){console.error('[Main App] Error signing in anonymously:',error)}}})}catch(error){console.error("[Main App] Error initializing Firebase or auth: ",error)}}
function initializeAllApps(){initializeMainFirebaseApp();initializeExternalVisitorCounter()}
document.addEventListener('DOMContentLoaded',initializeAllApps);function enforceCleanUrl(){const currentPath=window.location.pathname;const currentUrl=window.location.href;if(currentPath.endsWith('/')&&currentPath.length>1){const cleanPath=currentPath.replace(/\/+$/,'');const cleanUrl=window.location.origin+cleanPath+window.location.search+window.location.hash;console.log(`URL Found slash at the end: ${currentUrl}`);console.log(`Change URL without reloading: ${cleanUrl}`);history.replaceState(null,null,cleanUrl)}else{console.log(`URL is clean or root URL: ${currentUrl}`)}}
document.addEventListener('DOMContentLoaded',enforceCleanUrl)
